## Softmax and Cross-Entropy

In [17]:
import numpy as np

In [9]:
def softmax(x):
    x -= np.max(x)
    
    return np.exp(x) / np.sum(np.exp(x))

In [10]:
softmax([1.3, 2.4, -0.8])

array([0.24232893, 0.72799634, 0.02967474])

In [79]:
def cross_entropy(label, s):
	return -sum([label[i]*np.log(s[i]) for i in range(len(label))])

In [80]:
L = [0.10, 0.40, 0.50]
S = [0.80, 0.15, 0.05]

In [81]:
cross_entropy(L, S)

2.279028485862769

In [82]:
L2 = [0.5, 0.4, 0.1]

In [83]:
cross_entropy(L2, S)

1.1699929969668565

## 如果是一个5分类问题，那么当loss大于多少的时候，才能证明这个模型是“学习了的”？

In [84]:
L = [1, 0]
S = [0.5, 0.5]

cross_entropy(L, S)

0.6931471805599453

In [85]:
L = [1, 0, 0, 0, 0]
S = [0.25, 0.25, 0.25, 0.25, 0.25]

cross_entropy(L, S)

1.3862943611198906

In [86]:
L = [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
S = [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]

In [87]:
cross_entropy(L, S)

2.3025850929940455

## One-Hot

In [90]:
cities = [
    '北京',
    '南京',
    '大连',
    '青岛',
    '上海',
    '深圳',
    '杭州'
]

In [91]:
person1 = ['北京', 23]
person2 = ['南京', 24]
person3 = ['北京', 24]

In [92]:
from collections import defaultdict

In [95]:
def one_hot_encoder(features):
    onehot_encoder = defaultdict(lambda : [0] * len(set(features)))
    
    for i, f in enumerate(set(features)):
        onehot_encoder[f][i] = 1
        
    return onehot_encoder

In [96]:
one_hot_encoder(cities)

defaultdict(<function __main__.one_hot_encoder.<locals>.<lambda>()>,
            {'深圳': [1, 0, 0, 0, 0, 0, 0],
             '上海': [0, 1, 0, 0, 0, 0, 0],
             '北京': [0, 0, 1, 0, 0, 0, 0],
             '青岛': [0, 0, 0, 1, 0, 0, 0],
             '杭州': [0, 0, 0, 0, 1, 0, 0],
             '南京': [0, 0, 0, 0, 0, 1, 0],
             '大连': [0, 0, 0, 0, 0, 0, 1]})

In [101]:
def one_hot_decoder(x, decoder):
    v = []
    
    for i in x:
        if i in decoder: v += decoder[i]
        else:
            v.append(i)
        
    return v

In [105]:
one_hot_decoder(person1, one_hot_encoder(cities))

[0, 0, 1, 0, 0, 0, 0, 23]

In [106]:
one_hot_decoder(person2, one_hot_encoder(cities))

[0, 0, 0, 0, 0, 1, 0, 24]

In [107]:
one_hot_decoder(person3, one_hot_encoder(cities))

[0, 0, 1, 0, 0, 0, 0, 24]

In [108]:
from sklearn.preprocessing import OneHotEncoder

In [128]:
enc = OneHotEncoder()

In [130]:
enc.fit([[c] for c in cities])

OneHotEncoder(categorical_features=None, categories=None,
       dtype=<class 'numpy.float64'>, handle_unknown='error',
       n_values=None, sparse=True)

In [132]:
enc.transform([['北京'], ['南京'], ['大连']]).toarray()

array([[0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.]])

## Normalizationi and Standarlized 

In [134]:
#https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html
#https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html#sklearn.preprocessing.MinMaxScaler

In [141]:
## normalize

In [148]:
incomes = [[111212131], [32313111], [32431131], [34353311]]

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

normal = MinMaxScaler()
scalar = StandardScaler()

print('\nbefore processing')
print(incomes)
normal.fit(incomes)
incomes = normal.transform(incomes)

print('\nafter normalized')
print(incomes)

scalar.fit(incomes)

incomes_after_processed = scalar.transform(incomes)

print('\nafter standarlized')
print(incomes_after_processed)



before processing
[[111212131], [32313111], [32431131], [34353311]]

after normalized
[[1.        ]
 [0.        ]
 [0.00149584]
 [0.02585837]]

after standarlized
[[ 1.73155534]
 [-0.59843008]
 [-0.59494481]
 [-0.53818046]]


In [149]:
incomes_with_debt = [[111212131, -123141], [32313111, -123141], [32431131, -4534642], [34353311, -3252342]]

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

normal = MinMaxScaler()
scalar = StandardScaler()

print('\nbefore processing')
print(incomes_with_debt)
normal.fit(incomes_with_debt)
incomes = normal.transform(incomes_with_debt)

print('\nafter normalized')
print(incomes_with_debt)

scalar.fit(incomes_with_debt)

incomes_after_processed = scalar.transform(incomes_with_debt)

print('\nafter standarlized')
print(incomes_after_processed)



before processing
[[111212131, -123141], [32313111, -123141], [32431131, -4534642], [34353311, -3252342]]

after normalized
[[111212131, -123141], [32313111, -123141], [32431131, -4534642], [34353311, -3252342]]

after standarlized
[[ 1.73155534  0.97227959]
 [-0.59843008  0.97227959]
 [-0.59494481 -1.30295282]
 [-0.53818046 -0.64160637]]
